package practica3adapter_barcocoche;

/**
 *
 * @author Jonathan
 */
public class Ventana extends javax.swing.JFrame {

    Mandos barco, coche;

    public Ventana() {
        initComponents();
        barco = new Adaptador(jLabelBarco);
        coche = new Coche(jLabelCoche);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBarco = new javax.swing.JPanel();
        jButtonEncenderBarco = new javax.swing.JButton();
        jButtonAcelerarBarco = new javax.swing.JButton();
        jButtonApagarBarco = new javax.swing.JButton();
        jLabelBarco = new javax.swing.JLabel();
        jPanelCoche = new javax.swing.JPanel();
        jButtonEncenderCoche = new javax.swing.JButton();
        jButtonAcelerarCoche = new javax.swing.JButton();
        jButtonApagarCoche = new javax.swing.JButton();
        jLabelCoche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBarco.setBorder(javax.swing.BorderFactory.createTitledBorder("Barco"));

        jButtonEncenderBarco.setText("Encender");
        jButtonEncenderBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderBarcoActionPerformed(evt);
            }
        });

        jButtonAcelerarBarco.setText("Acelerar");
        jButtonAcelerarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarBarcoActionPerformed(evt);
            }
        });

        jButtonApagarBarco.setText("Apagar");
        jButtonApagarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarBarcoActionPerformed(evt);
            }
        });

        jLabelBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paradoBarco.jpg"))); // NOI18N
        jLabelBarco.setText("jLabel1");
        jLabelBarco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelBarcoLayout = new javax.swing.GroupLayout(jPanelBarco);
        jPanelBarco.setLayout(jPanelBarcoLayout);
        jPanelBarcoLayout.setHorizontalGroup(
            jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarcoLayout.createSequentialGroup()
                .addComponent(jLabelBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEncenderBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcelerarBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonApagarBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBarcoLayout.setVerticalGroup(
            jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarcoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBarco)
                        .addComponent(jButtonAcelerarBarco))
                    .addGroup(jPanelBarcoLayout.createSequentialGroup()
                        .addComponent(jButtonEncenderBarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonApagarBarco)))
                .addGap(19, 19, 19))
        );

        jPanelCoche.setBorder(javax.swing.BorderFactory.createTitledBorder("Coche"));

        jButtonEncenderCoche.setText("Encender");
        jButtonEncenderCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderCocheActionPerformed(evt);
            }
        });

        jButtonAcelerarCoche.setText("Acelerar");
        jButtonAcelerarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarCocheActionPerformed(evt);
            }
        });

        jButtonApagarCoche.setText("Apagar");
        jButtonApagarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarCocheActionPerformed(evt);
            }
        });

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paradoCoche.png"))); // NOI18N
        jLabelCoche.setText("jLabel1");
        jLabelCoche.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCocheLayout = new javax.swing.GroupLayout(jPanelCoche);
        jPanelCoche.setLayout(jPanelCocheLayout);
        jPanelCocheLayout.setHorizontalGroup(
            jPanelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCocheLayout.createSequentialGroup()
                .addComponent(jLabelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEncenderCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcelerarCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonApagarCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCocheLayout.setVerticalGroup(
            jPanelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCocheLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCoche)
                        .addComponent(jButtonAcelerarCoche))
                    .addGroup(jPanelCocheLayout.createSequentialGroup()
                        .addComponent(jButtonEncenderCoche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonApagarCoche)))
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Práctica 3 : Adapter - Arquitectura Software Dirigida por Modelos");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Jonathan Jiménez Reina - 3º Ingeniería Informática de Software ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelCoche.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncenderBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderBarcoActionPerformed
        barco.encender();
    }//GEN-LAST:event_jButtonEncenderBarcoActionPerformed

    private void jButtonEncenderCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderCocheActionPerformed
        coche.encender();
    }//GEN-LAST:event_jButtonEncenderCocheActionPerformed

    private void jButtonAcelerarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarBarcoActionPerformed
        barco.acelerar();
    }//GEN-LAST:event_jButtonAcelerarBarcoActionPerformed

    private void jButtonApagarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarBarcoActionPerformed
        barco.apagar();
    }//GEN-LAST:event_jButtonApagarBarcoActionPerformed

    private void jButtonAcelerarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarCocheActionPerformed
        coche.acelerar();
    }//GEN-LAST:event_jButtonAcelerarCocheActionPerformed

    private void jButtonApagarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarCocheActionPerformed
        coche.apagar();
    }//GEN-LAST:event_jButtonApagarCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcelerarBarco;
    private javax.swing.JButton jButtonAcelerarCoche;
    private javax.swing.JButton jButtonApagarBarco;
    private javax.swing.JButton jButtonApagarCoche;
    private javax.swing.JButton jButtonEncenderBarco;
    private javax.swing.JButton jButtonEncenderCoche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBarco;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JPanel jPanelBarco;
    private javax.swing.JPanel jPanelCoche;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
